### PR TITLE
Add support for Netlify

### PR DESCRIPTION
**Pull request by gozer**
- Add netlify.toml
 - Add contribute.json

### CODE REVIEW

**Comment by cr** [comment]
Ohai @gozer, can you elaborate what's going on in this PR and why we want to have this?

**Comment by cr** [comment]
No comment, @gozer?

**Comment by gozer** [comment]
Oh, it's because we are looking at transitionning all our static sites into a provider called Netlify, and for that, it needs a netlify.toml to hold the site's configuration.

It's not a provider we are actually using quite yet, but I've been testing things out and having this merged would simplify my life. I've been using a fork for now, but it means that I need to manually pull from this repo to make sure changes are synchronized.

**Comment by cr** [comment]
Okay, thanks!

**Pull request merged**
